# Generated by Django 2.1.7 on 2019-03-07 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('image_path', models.CharField(max_length=100, verbose_name='图片链接')),
            ],
            options={
                'db_table': 'carousel',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, verbose_name='课程类别')),
            ],
            options={
                'db_table': 'course_category',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('grade', models.FloatField(verbose_name='评分')),
                ('suitable_for_croud', models.CharField(max_length=100, verbose_name='适用人群')),
                ('image_url', models.CharField(max_length=200, verbose_name='图片链接地址')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Category')),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
