# Generated by Django 2.1.7 on 2019-03-09 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('sum', models.IntegerField(verbose_name='订单总价')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='订单生成时间')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='user.Course', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
